# Generated by Django 6.0.5 on 2026-07-01 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_event_name', models.CharField(max_length=200)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_unit', models.CharField(choices=[('PLATES', 'Plates'), ('KG', 'Kg'), ('BOXES', 'Boxes'), ('PACKETS', 'Packets'), ('LITERS', 'Liters'), ('OTHER', 'Other')], max_length=20)),
                ('expiry_hours', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('other_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to='location.location')),
            ],
        ),
    ]
