# Generated by Django 6.0.5 on 2026-07-02 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_CLAIMED', 'Partially Claimed'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('accepted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('receiver_full_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='food.foodlisting')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('food_listing', 'receiver')},
            },
        ),
    ]
